### ISSUE TITLE
Space and availability

### ISSUE THREAD

**Issue by coder-nigga** [collegenarad/CollegeNarad#5]
1. Contributors may hold back as they might not be willing to share a permanent space in their drive indefinitely. Again, **deletion of the content by the contributor after any span of time** will render the URL void, which can create unforeseen discomfort.
Instead, we could opine to collect all the content in a "**hub**" that is secure and accessible at all times.

**Comment by rdrsadhu** [comment]
Noted.
Thanks @coder-nigga for bringing this up.
